name: SpotifyTopTracksTM
author: TobiMichael96
description: Show your Spotify top tracks in your GitHub account!
branding:
  icon: user-check
  color: gray-dark

runs:
  using: 'node16'
  main: 'index.js'